feat: add toggle preview json to copy to manifest.json
NotWoods/maskable pull request #54
Opened 2021-05-17 13:44 UTC by alexalannunes

2021-05-18 02:58 UTC, NotWoods requested changes
I like this feature idea! I'd like to replace some code with native tools that achieve the same effect. It would also be great to have some help text above/below the JSON that says where to put it. You can use: 
>Copy this JSON into the `"icons"` array of your [Web App Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest)

2021-05-18 02:58 UTC, NotWoods commented on editor.html
> +            <a href="#" class="dialog-action-link" id="showPreviewArrayIcons">Show JSON</a>
I'd like to use the `<details>`/`<summary>` elements instead to do the open/close without Javascript.

2021-05-18 02:58 UTC, NotWoods commented on src/editor/export.js
> +  outputPreview.textContent = JSON.stringify(filteredJson, null, 2);
Updating the text is cheap enough that we can just change it everytime the selected checkboxes are changed. That also removes the need for a separate array, you can read `sizeInputs`.

2021-07-28 16:39 UTC, alexalannunes commented
Hi @NotWoods. I'm worning on it!

2024-07-23 19:05 UTC, closed without merging